app:
  build: .
  volumes:
    - .:/usr/src/app
  ports:
    - "8080:8080"
proxy:
  image: nginx
  volumes:
    - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf
    - ./public:/var/www
  links:
    - app:app
  ports:
    - "80:80"
